### ISSUE TITLE
Add --mypy-config option

### ISSUE THREAD

**Issue by pbelskiy** [dbader/pytest-mypy#110]
Hello! I have not found how to pass path to mypy config?

I want something like: pytest --mypy --mypy-config tox.ini

It's because mypy isn't read config from tox.

**Comment by dmtucker** [comment]
Hey there :wave: I would recommend implementing a `pytest_configure` hook in `conftest.py` for this:
``` python
def pytest_configure(config):
    plugin = config.pluginmanager.getplugin("mypy")
    plugin.mypy_argv.extend(["--config-file", "tox.ini"])
```

**Comment by ngie-eign** [comment]
@dmtucker: doing this would require implementing it in every `conftest.py` file, which would degrade the usability for end-users and increase unnecessary repetition in the source code.

**Comment by dmtucker** [comment]
> in every `conftest.py` file

`conftest.py` files should cascade (i.e. `tests/conftest.py` should apply to `tests/foo/*` and `tests/bar/*`, etc).

Maybe I'm not understanding the issue? :thinking: 

> across multiple projects

Most projects won't need this, and I _really_ don't want to get into the business of mirroring `mypy`'s CLI.
Moreover, I don't see how this solves your problem... You would still need to change the `pytest` invocation (e.g. in `tox.ini`) for every project to use `--mypy-config`.

If you want to be able to control how multiple `pytest` projects run in a single place, I would suggest making an installable plugin and adding it as a dependency to each of your projects. Then, you would only need to change that plugin and publish it in order to affect all your projects.

**Comment by Mohsin-Ul-Islam** [comment]
@dmtucker I am using Bazel to run pytest across my python libraries and services in a monorepo. Since Bazel builds everything in a separate environment I cannot pass the config file path to the plugin in conftest.py, I have to define the path in Bazel's BUILD file. But the only way to pass config file path in Bazel's BUILD file is via flag to this plugin.
