### ISSUE TITLE
Make a conda package

### ISSUE THREAD

**Issue by hameerabbasi** [dbader/pytest-mypy#24]
As title. Would be very useful. :-)

**Comment by dmtucker** [comment]
Unfortunately, I know pretty much nothing about conda 😕 
This seems like a fine thing for Travis CI to do automatically if that's possible, but we may need @dbader to help us set that up. Currently, I manually deploy to PyPI because I don't have perms to generate deploy creds for Travis (afaik)... I'm not too keen to add more manual steps to the release process.

**Comment by neozenith** [comment]
@dmtucker if you have permissions to TravisCI as a collaborator you should be able to add Secure Enironment Variables in the Repository Settings.

The catch is forked Pull Requests do not have access to those credentials. Only PRs from branches on the owner repo or manual runs on master have access to those runs.

You can use the environment variable TRAVIS_PULL_REQUEST to help.

I've just gone through a similar issue on VCRpy where I'm not the owner but a collaborator. So I can't re-encrypt secrets for the travis.yml file.

**Comment by hameerabbasi** [comment]
If conda-forge is okay, I can make a PR with a recipe. It's as close to automated as it gets.

**Comment by sduc** [comment]
I went ahead a created a PR on conda-forge: https://github.com/conda-forge/staged-recipes/pull/10848

**Comment by dmtucker** [comment]
Thanks @sduc! Is that all that's needed to resolve this issue?

**Comment by sduc** [comment]
Yes! pytest-mypy is now available on conda-forge. They merge my PR. I believe we can close this out.
